# Netlify configuration file

[build]
  # The directory where your site's publishable files are located
  publish = "/"

[functions]
  # The directory where Netlify will find your serverless functions
  directory = "netlify/functions/"
